[project]
name = "chronos-lens"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.6.0",
    "numpy",
    "pandas",
    "scikit-learn",
    "tqdm",
    "pyyaml",
    "matplotlib",
    "google-auth",
    "google-cloud-bigquery",
    "db-dtypes",
    "pyarrow",
    "umap-learn",
    "phate",
    "pingouin",
    "tensorboard",
    "xgboost",
    "hdbscan",
    "scipy",
    "dotenv>=0.9.9",
    "boto3>=1.43.24",
]

[tool.setuptools.packages.find]
where = ["."]
